### ISSUE TITLE
Occasionally the music stops and the app breaks

### ISSUE THREAD

**Issue by noahsark769** [calband/calchart-viewer#146]
Not sure why this happens or how to reproduce it, but it happened twice during music rehearsal this year - the only thing I'm sure of is that both times it happened with shows that had a midi track (though it MIGHT happen for shows with a non-midi track also).

Refreshing the page worked, and both times it worked on the second time. Not really sure what the cause might be but it's kind of embarrassing to have the app stop working in front of the whole band, haha.

**Comment by brandonchinn178** [comment]
wont fix wtf
