### ISSUE TITLE
Grapher should draw tunnel

### ISSUE THREAD

**Issue by noahsark769** [calband/calchart-viewer#15]
**Blocking this issue**: ~~#13~~ Fixed by #25 

**Description**: We need to be able to draw tunnel as well. The `Grapher` object should be able to accept "tunnel" as a field type, and draw an svg depiction of the north tunnel from memorial exactly as calchart does.

**Comment by noahsark769** [comment]
@kmdurand we can probably close this as a wontfix right

**Comment by brandonchinn178** [comment]
@kmdurand wont fix?

**Comment by noahsark769** [comment]
Given that this has been open for more than two years and we haven't needed it enough to build it, I'm gunna say close.
