### ISSUE TITLE
Mobilify

### ISSUE THREAD

**Issue by brandonchinn178** [calband/calchart-viewer#160]
What if we had another page, mobile.html, that is the mobile app of the site? If a user accessed the main page on a mobile device, Javascript will check it and redirect to mobile.html, which can be a simple UI for use in rehearsal. I'm thinking it shows a stuntsheet at a time, with controls to advance to the next stuntsheet. What do you think?

**Comment by noahsark769** [comment]
I actually don't think this is necessary. I feel that using this in rehearsal wouldn't really be viable because you would just use the PDF right?

**Comment by brandonchinn178** [comment]
What if hypothetically people just want quick directions on their phone? Like maybe Friday/Saturday rehearsals
