### ISSUE TITLE
Push script

### ISSUE THREAD

**Issue by noahsark769** [calband/calchart-viewer#176]
It might be nice to have an automated way to deploy the site, instead of just manually checking out gh-pages and gitignoring that stuff every deploy. I wrote something like this at https://github.com/noahsark769/noahgilmore.com/blob/master/scripts/push.py, perhaps we could adopt it in some form.

**Comment by brandonchinn178** [comment]
+1 one thing I did at my work was a script that basically did:

```
git clone <repo>
git checkout -b gh-pages --orphan
# build any files
# could even remove .gitignore for this branch
git push -f origin gh-pages
```

Since the `gh-pages` branch doesn't care about having a history. Down for this idea?
